import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/DashboardChild";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conversur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='w-lvw h-lvh flex bg-background font-poppins'>
          <Dashboard/>
          {children}
      </div>
      </body>
    </html>
  );
}
