"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import Dashboard from "@/components/DashboardChild";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Conversur",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isLoginPage = usePathname() === "/login";
  const isRegisterPage = usePathname() === "/register";
  const shouldRenderDashboard = !isLoginPage && !isRegisterPage;

  return (
    <html lang="en">
      <head>
        <title>Conversur</title>
      </head>
      <body className={inter.className}>
        <div className="w-lvw h-lvh flex bg-background font-poppins">
          {shouldRenderDashboard && <Dashboard />}
          {children}
        </div>
      </body>
    </html>
  );
}
