import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastContext from "@/context/ToastContext";
import { getServerSession } from "next-auth";
import SessionProvider from '@/lib/SessionProvider'
import ReduxProvider from "@/redux/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conversur",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <ReduxProvider>
        <SessionProvider session={session}>
          <body className={inter.className}>
            <ToastContext />
            <div className="w-lvw h-lvh flex bg-background font-poppins">
              {children}
            </div>
          </body>
        </SessionProvider>
      </ReduxProvider>
    </html>
  );
}
